# -*- coding: utf-8 -*-
"""language_model_analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Lp-GTpxBnUZqc9j-G0TnmD2SqCu34Jpr
"""

!pip install transformers

from transformers import pipeline
import matplotlib.pyplot as plt

generator = pipeline("text-generation", model="gpt2")

result = generator("Artificial Intelligence will", max_length=30)

print(result)

generator = pipeline("text-generation", model="gpt2")

result = generator("Artificial Intelligence will", max_length=30)

print(result)

text1 = generator("Machine learning is", max_length=30)
text2 = generator("The future of AI is", max_length=30)

print(text1)
print(text2)

sentiment = pipeline("sentiment-analysis")

print(sentiment("I love artificial intelligence"))
print(sentiment("AI models are difficult"))

labels = ["Positive", "Negative"]
values = [70, 30]

plt.bar(labels, values)
plt.title("Sentiment Analysis Results")
plt.xlabel("Sentiment")
plt.ylabel("Percentage")
plt.show()